/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssetSchema extends BaseModel {
  static $columns = ['assetType', 'barcode', 'brand', 'createdAt', 'id', 'name', 'purchasePrice', 'roomId', 'updatedAt'] as const
  $columns = AssetSchema.$columns
  @column()
  declare assetType: string | null
  @column()
  declare barcode: string | null
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare purchasePrice: number | null
  @column()
  declare roomId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BuildingSchema extends BaseModel {
  static $columns = ['buildingArea', 'campusId', 'createdAt', 'description', 'id', 'landArea', 'name', 'totalFloors', 'updatedAt'] as const
  $columns = BuildingSchema.$columns
  @column()
  declare buildingArea: number | null
  @column()
  declare campusId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare landArea: number | null
  @column()
  declare name: string | null
  @column()
  declare totalFloors: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampusSchema extends BaseModel {
  static $columns = ['address', 'areaSize', 'contact', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = CampusSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare areaSize: number | null
  @column()
  declare contact: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MaintenanceLogSchema extends BaseModel {
  static $columns = ['actionTaken', 'createdAt', 'id', 'inspectionCode', 'repairCost', 'sloValidationId', 'technicianId', 'updatedAt'] as const
  $columns = MaintenanceLogSchema.$columns
  @column()
  declare actionTaken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inspectionCode: string | null
  @column()
  declare repairCost: number | null
  @column()
  declare sloValidationId: string | null
  @column()
  declare technicianId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoomSchema extends BaseModel {
  static $columns = ['buildingId', 'capacity', 'category', 'createdAt', 'description', 'floor', 'height', 'id', 'length', 'name', 'updatedAt', 'width'] as const
  $columns = RoomSchema.$columns
  @column()
  declare buildingId: string
  @column()
  declare capacity: number | null
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare floor: number | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare length: number | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number | null
}

export class SloCertificateSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'id', 'name', 'sloCode', 'status', 'updatedAt', 'userId'] as const
  $columns = SloCertificateSchema.$columns
  @column()
  declare assetId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare sloCode: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SloChecklistItemSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'id', 'indicator', 'updatedAt'] as const
  $columns = SloChecklistItemSchema.$columns
  @column()
  declare assetId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare indicator: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SloValidationSchema extends BaseModel {
  static $columns = ['condition', 'createdAt', 'estimatedRepairCost', 'id', 'requiresPowerOutage', 'sloCertificateId', 'updatedAt'] as const
  $columns = SloValidationSchema.$columns
  @column()
  declare condition: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare estimatedRepairCost: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare requiresPowerOutage: boolean | null
  @column()
  declare sloCertificateId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SloValidationCheckSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isPassed', 'sloChecklistItemId', 'sloValidationId', 'updatedAt'] as const
  $columns = SloValidationCheckSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPassed: boolean | null
  @column()
  declare sloChecklistItemId: string | null
  @column()
  declare sloValidationId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SloValidationImageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'path', 'sloValidationId', 'updatedAt'] as const
  $columns = SloValidationImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string | null
  @column()
  declare sloValidationId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
